# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile

#
# BSD 3-Clause License

FROM python:3.10-slim

WORKDIR /app

COPY pyproject.toml pyproject.toml
COPY LICENSE LICENSE
COPY README.md README.md
COPY skyfi_mcp_server/* skyfi_mcp_server/

RUN pip install -e .

CMD ["python", "-m", "skyfi-mcp-server.server"]
